kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
    # these don't change with deployments
    #  - service.yaml
    #  - ingress.yaml

namespace: app-space

configMapGenerator:
- name: my-config-map
  files:
    - files/sample-file.txt

